[package]
name = "lofty_attr"
version = "0.8.0"
authors = ["Serial <69764315+Serial-ATA@users.noreply.github.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Macros for Lofty"
repository = "https://github.com/Serial-ATA/lofty-rs"
readme = "README.md"
include = ["src", "Cargo.toml", "../LICENSE-*"]

[dependencies]
syn = { version = "2.0.15", features = ["full", "parsing"] }
quote = "1.0.26"
proc-macro2 = "1.0.56"

[lib]
proc-macro = true
